In [ ]:
import numpy as np

**Valid Sudoku**

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
np.sum(s,axis = 1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
np.sum(s,axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
s.sum()

np.int64(405)

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n = s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


**General Questions**

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape


(5, 3)

In [ ]:
#Find the average age of students.
data.mean(axis=0)

array([18.4, 81.6, 83.2])

In [ ]:
#Extract Math marks of all students.
data[: , 1]

array([85, 92, 76, 65, 90])

In [ ]:
#Find the highest Science mark.
data[: , 2].max()

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.

data[data[:,1] > 90]

array([[19, 92, 88]])

In [ ]:
#Increase Math marks of all students by 5.
data[:,1] + 5

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.
data[data[:,0] < 19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [ ]:
#Calculate the average marks in each subject (column-wise mean).
data[:,1:].mean(axis = 0)

array([81.6, 83.2])

In [ ]:
 #Get data of students who scored at least 80 in both subjects.
# data[:,1:] > 80
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])