In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [12]:
matrix_array = np.array([[1,2,3,4],[5,6,7,8]])
matrix_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
np.random.rand(12)

array([0.37585497, 0.35499707, 0.51123247, 0.64888855, 0.41924482,
       0.10413728, 0.55706152, 0.9419854 , 0.64287058, 0.2208113 ,
       0.5939876 , 0.25959248])

In [14]:
np.random.randn(10)

array([-0.70695018, -0.09025577, -1.53366048, -0.20945981, -0.6888447 ,
       -0.74651752,  0.95475668,  0.14335882, -1.67448909,  1.63265642])

In [17]:
arr = np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
new_array = np.arange(11,21)
new_arrayre = new_array.reshape(2,5)
new_arrayre

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
arr.shape

(2, 5)

In [26]:
arr.dtype

dtype('int64')

In [28]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.min

<function ndarray.min>

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.argmax()

np.int64(8)

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
arr[2: ,2: ]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [35]:
arr[0:2 , 1:3]

array([[2, 3],
       [7, 8]])

In [37]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])