In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)
arr2

array([5, 6, 7, 8])

In [4]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [5]:
arr1 - arr2

array([-4, -4, -4, -4])

In [6]:
arr1 * arr2

array([ 5, 12, 21, 32])

In [7]:
arr1 / arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [10]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [11]:
arr1 @ arr2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [12]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [14]:
#Stacking and splitting

In [15]:
arr1 = np.arange(1,5)
arr2 =np.arange(5,9)


In [16]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.column_stack((arr1,arr2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [23]:
arr1 = np.arange(1,37).reshape(6,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [25]:
np.hsplit(arr1,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21],
        [25, 26, 27],
        [31, 32, 33]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24],
        [28, 29, 30],
        [34, 35, 36]])]

In [26]:
np.vsplit(arr1,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]